language: python
python:
  - '3.2'
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.6'
before_install:
  - apt-get install pandoc
install: make install
before_script:
  - pip install -r requirements.txt
script: 
  - flake8
  - make test
