language: python
python:
  - '3.8'
before_install:
  - sudo apt-get install pandoc
install: make install
before_script:
  - pip install -r requirements.txt
script: 
  - flake8
  - make test
branches:
  only:
  - master
