name: python

on: [pull_request]

jobs:
  test:
    runs-on: python:3.10-bullseye

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Poetry
      run: |
        pip install poetry==1.8.3

    - name: Install dependencies
      run: |
        poetry config virtualenvs.create false && poetry install --only main

    - name: Install make
      run: |
        sudo apt-get update
        sudo apt-get install -y make

    - name: Run tests
      run: |
        make test