name: python

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Poetry
      run: |
        pip install poetry==1.8.3

    - name: Configure Poetry
      run: |
        poetry config virtualenvs.in-project true

    - name: Cache the virtualenv
      uses: actions/cache@v3
      with:
        path: ./.venv
        key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-venv-

    - name: Install dependencies
      run: |
        poetry install

    - name: Install make
      run: |
        sudo apt-get update
        sudo apt-get install -y make

    - name: Run tests
      run: |
        make test